openapi: 3.1.0
info:
  title: Webhook Example
  version: 1.0.0
security: # globle security setting
  - token: []
paths:
  # OpenAPI documents all need a paths element
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      security:
        - HMACAuth: []
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
        - name: author
          in: query
          description: author field test
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
    post:
      tags:
        - Room_voucher
      security:
        - HMACAuth: []
      x-oasis-name-space: Openapi.room_voucher
      requestBody:
        $ref: "#/components/requestBodies/roomVoucherAssign"
      responses:
        "200":
          description: CBE Room Voucher Assign
          content:
            application/json:
              schema:
                type: object
                required:
                  - code
                properties:
                  code:
                    type: integer
                    enum:
                      - 0
        default:
          $ref: "#/components/responses/error"
  /get_pet:
    get:
      summary: Get a pet infos
      operationId: GetPet
      parameters:
        - name: id
          in: query
          description: Get a pet infomation
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A pet infomation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /get_pet2/{id}:
    parameters:
      - name: lang
        in: query
        description: Get a pet infomation
        required: false
        schema:
          type: integer
    get:
      summary: Get a pet infos, method 2
      operationId: GetPet2
      parameters:
        - name: id
          in: path
          description: Get a pet infomation
          schema:
            type: integer
        - name: lang
          in: query
          description: Get a pet infomation
          required: false
          schema:
            type: string
        - name: author
          in: query
          description: author field test
          required: false
          schema:
            type: string
        # - name: x-cbe-content-sha256
        - name: x-cbe-content-SHA256
          in: header
          description: header field test
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A pet infomation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"



webhooks:
  # Each webhook needs a name
  newPet:
    # This is a Path Item Object, the only difference is that the request is initiated by the API provider
    post:
      requestBody:
        description: Information about a new pet in the system
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: Return a 200 status to indicate that the data was received successfully

components:
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"

  securitySchemes:
      token:
        type: http
        scheme: bearer
        x-oasis-name-space: Openapi
        x-oasis-key-to-assigns: token
      HMACAuth:
        type: http
        scheme: hmac-sha256
        x-oasis-signed-headers: date;x-cbe-content-sha256
  
  requestBodies:
    roomVoucherAssign:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/roomVoucherAssign"
        
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"

    phone_number:
      type: string
    transaction_id:
      type: string
      minLength: 9
      maxLength: 32
      example: 6fa459eaee8a3ca4894edb77e160355e
    room_voucher_id:
      type: string
      minLength: 12
      example: 0RkVXoQ1DL4O
    room_voucher_num:
      type: integer
      example: 1

    error:
      type: object
      required:
        - error_code
        - error_message
      properties:
        error_code:
          type: integer
        error_message:
          type: string
    roomVoucherAssign:
      type: object
      required:
        - transaction_id
        - phone
        - room_voucher_id
        - room_voucher_num
      properties:
        transaction_id:
          $ref: "#/components/schemas/transaction_id"
        phone:
          $ref: "#/components/schemas/phone_number"
        room_voucher_id:
          $ref: "#/components/schemas/room_voucher_id"
        room_voucher_num:
          $ref: "#/components/schemas/room_voucher_num"
